# 🛍️ Reinforcement Bars Analysis Project

## 📌 Introduction

This dataset contains structural reinforcement (rebar) schedules and details extracted from a 
Building Information Modeling (BIM) or structural detailing software (such as Revit) for an air-cooled
building and outer structures project. It includes physical specifications of the 
reinforcement bars (such as diameter, length, volume, and weight), quantities, host element 
properties (e.g., Beams, Structural Framing), and structural classification tags. This data is 
essential for material takeoff, cost estimation, structural analysis, and construction logistics

<span style="font-size:2em; color:orange;"><b>Helper Libraries</b></span>

In [2]:
# import helper libraries
import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
import plotly.io as pio

color_template = {
    "layout": {
        "width": 700,
        "height": 500,
        "colorway": [
            "#AFA9E9", "#8FDBA8", "#CF98AA", "#7C3C60", "#740580",
            "#18A999", "#5A20CB", "#FFB200", "#06D6A0", "#118AB2",
            "#EF476F", "#FFD166", "#073B4C", "#8338EC", "#FB5607"
        ],
        "plot_bgcolor": "#F8E6F8",   
        "paper_bgcolor": "#F8E6F8",  
        "font": {"family": "Arial", "size": 14, "color": "#333"},
        
        # --- UPDATED AXIS SETTINGS ---
        "xaxis": {
            "showgrid": True,          # Turn on grid lines
            "gridcolor": "#FFFFFF",    # Make grid lines white to contrast the pink background
            "showline": True,          # Turn on the main X axis line
            "linecolor": "#333333",    # Dark gray axis line
            "linewidth": 1             # Thickness of the axis line
        },
        "yaxis": {
            "showgrid": True,          # Turn on grid lines
            "gridcolor": "#FFFFFF",    # Make grid lines white
            "showline": True,          # Turn on the main Y axis line
            "linecolor": "#333333",    # Dark gray axis line
            "linewidth": 1             # Thickness of the axis line
        },
        
        "title": {"font": {"size": 20, "color": "#740580"}},
    }
}

# Register & set as default
pio.templates["custom_theme"] = color_template
pio.templates.default = "custom_theme"


<span style="font-size:2em; color:orange;"><b>Dataset Expolation</b></span>

In [4]:
# import dataset
df = pd.read_csv('Reinforcement Bars.csv')

In [5]:
df = df.iloc[:-1]

In [6]:
df

,Bar Diameter,Maximum bar length,Reinforcement Volume,Rebar Number,Mark,Total Bar Length,Quantity,Workset,Host Category,Host Mark,REBAR-PARTITION,WEIGHT IN KG,Style,Bend Diameter
0,8 mm,1135 mm,1483.00 cm³,1752.0,1644.0,29503 mm,26,STR-Model,Structural Framing,B 250X400,Beam,11.656372,Stirrup / Tie,64 mm
1,8 mm,1135 mm,456.31 cm³,1752.0,1644.0,9078 mm,8,STR-Model,Structural Framing,B 250X400,Beam,3.586576,Stirrup / Tie,64 mm
2,8 mm,1135 mm,798.54 cm³,1752.0,1644.0,15886 mm,14,STR-Model,Structural Framing,B 250X400,Beam,6.276508,Stirrup / Tie,64 mm
3,8 mm,1135 mm,1483.00 cm³,1752.0,1644.0,29503 mm,26,STR-Model,Structural Framing,B 250X400,Beam,11.656372,Stirrup / Tie,64 mm
4,8 mm,1135 mm,1597.08 cm³,1752.0,1644.0,31773 mm,28,STR-Model,Structural Framing,B 250X400,Beam,12.553016,Stirrup / Tie,64 mm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6004,25 mm,6000 mm,70684.65 cm³,205.0,205.0,143998 mm,24,STR-Model,Structural Column,C1 900x900x10500,Column,555.581327,Standard,175 mm
6005,25 mm,8000 mm,94252.82 cm³,204.0,204.0,192010 mm,24,STR-Model,Structural Column,C1 900x900x10500,Column,740.827164,Standard,175 mm
6006,25 mm,6000 mm,70684.65 cm³,205.0,205.0,143998 mm,24,STR-Model,Structural Column,C1 900x900x10500,Column,555.581327,Standard,175 mm
6007,25 mm,8000 mm,94252.82 cm³,204.0,204.0,192010 mm,24,STR-Model,Structural Column,C1 900x900x10500,Column,740.827164,Standard,175 mm
6008,25 mm,6000 mm,70684.65 cm³,205.0,205.0,143998 mm,24,STR-Model,Structural Column,C1 900x900x10500,Column,555.581327,Standard,175 mm

In [7]:
df_summary = pd.DataFrame({
    'Data Columns': df.columns,
    'Data Type': df.dtypes.values,
    'Missing Values': df.isnull().sum().values,
    'Unique Values': df.nunique().values
})
df_summary

            Data Columns Data Type  Missing Values  Unique Values
0           Bar Diameter    object               0              7
1     Maximum bar length    object             401           1420
2   Reinforcement Volume    object               0           2783
3           Rebar Number   float64             401           2210
4                   Mark   float64             379           2100
5       Total Bar Length    object               0           2406
6               Quantity     int64               0             87
7                Workset    object               0              3
8          Host Category    object               0              6
9              Host Mark    object            3297             89
10       REBAR-PARTITION    object             122             88
11          WEIGHT IN KG   float64               0           2843
12                 Style    object               0              2
13         Bend Diameter    object               0              9

In [8]:
df.shape

(6009, 14)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6009 entries, 0 to 6008
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Bar Diameter          6009 non-null   object
 1   Maximum bar length    5608 non-null   object
 2   Reinforcement Volume  6009 non-null   object
 3   Rebar Number          5608 non-null   float64
 4   Mark                  5630 non-null   float64
 5   Total Bar Length      6009 non-null   object
 6   Quantity              6009 non-null   int64
 7   Workset               6009 non-null   object
 8   Host Category         6009 non-null   object
 9   Host Mark             2712 non-null   object
 10  REBAR-PARTITION       5887 non-null   object
 11  WEIGHT IN KG          6009 non-null   float64
 12  Style                 6009 non-null   object
 13  Bend Diameter         6009 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 657.4+ KB

<span style="font-size:2em; color:orange;"><b>Summary statistics about features (Descriptive Statistics)</b></span>

In [12]:
df.describe()

       Rebar Number         Mark     Quantity  WEIGHT IN KG
count   5608.000000  5630.000000  6009.000000   6009.000000
mean    1781.370007  1745.038721     9.757364     56.293552
std     1049.530550  1066.089972    17.019141    163.558405
min        1.000000     1.000000     1.000000      0.376194
25%      886.750000   777.000000     1.000000      4.076510
50%     1752.000000  1705.000000     3.000000     13.468178
75%     2608.250000  2624.750000    11.000000     44.446984
max     3626.000000  3543.000000   242.000000   3585.411731

In [13]:
df.describe(include = 'O')

,Bar Diameter,Maximum bar length,Reinforcement Volume,Total Bar Length,Workset,Host Category,Host Mark,REBAR-PARTITION,Style,Bend Diameter
count,6009,5608,6009,6009,6009,6009,2712,5887,6009,6009
unique,7,1420,2783,2406,3,6,89,88,2,9
top,16 mm,2770 mm,217.59 cm³,2770 mm,STR-Model,Wall,RAFT THICK. 1000 mm,VaCh2-REBAR,Standard,48 mm
freq,2043,281,281,281,3988,1571,447,538,4501,1710

In [14]:
df['Host Mark'].unique()

array(['B 250X400', 'TB1', 'ST-C1 250x400x8275', nan, 'OS MEP SUPPORT',
       'F3', 'F3A', 'F6', 'F12', 'F1', 'F9', 'F6A', 'F6B', 'F4A', 'F7',
       'C3 400x400x7500', 'W5', 'F5', 'PD1 300x300x2000',
       'C1 900x900x10500', 'C2 700x700x10500', 'C4 500x500x10500',
       'ST-C2 300x700x2000', 'ST-C2 250x700x8900', 'ST-C3 250x900x8865',
       'ST-C3 300x900x2000', 'W4', 'GB1', 'GB2', 'GB3', 'GB2A', 'SB4',
       'B24', 'B23', 'SB1', 'SB2', 'SB3', 'B7 (B400X500)',
       'B6 (B400X500)', 'B8 (B400X500)', 'B9 (B400X500)',
       'B10 (B400X650)', 'PD2 400x550x2900', 'PD2 400x550x4400',
       'PD3 800x900x2900', 'PD4 400x900x2900', 'PD4 400x900x4400',
       'PD5 550x800x2900', 'RAFT THICK. 1000 mm', 'PD0 300x300x1070',
       'P2 650X400X1250', 'P1 400X400X1250', 'AHU SHADE',
       'PC2 550X1300X1050', 'F2', 'W3', 'W1', 'W2', '200 THK. RC TRENCH',
       'Upstand', 'B25', 'B5 (B400X650)', 'B15T (B400X750T)',
       'B14T (B400X750T)', 'B13 (B400X650)', 'B12 (B400X600)',
       'B11 (B400X600)', 'B4L (B400X750L)', 'B14TA (B400X750T)',
       'B15TA (B400X750T)', 'B19L (B500X850L)', 'B21L (B500X850L)',
       'B17L (B400X750L)', 'B16L (B400X750L)', 'B17LA (B400X850L)',
       'B18L (B400X850L)', 'B1 (B400X650)', 'B2L (B400X750L)',
       'B3 (B400X750)', 'B15L (B400X750L)', 'B14L (B400X750L)', 'F10',
       'CT - FLOOR', 'STW1', 'PC1 550X550', 'B20L (B500X850L)',
       'B22 (B400X750)', 'F4', 'F11', 'STW2'], dtype=object)

In [15]:
df['Workset'].unique()

array(['STR-Model', 'STR-OUTER STRUCTURES', 'STR-TRENCH'], dtype=object)

In [16]:
# 2. Modify the "Workset" column using .replace()
df['Workset'] = df['Workset'].replace({
    'STR-Model': 'STR-Air Cooled Plant', 
    'STR-TRENCH': 'STR-Air Cooled Plant'
})
# 3. Display the updated DataFrame
df

,Bar Diameter,Maximum bar length,Reinforcement Volume,Rebar Number,Mark,Total Bar Length,Quantity,Workset,Host Category,Host Mark,REBAR-PARTITION,WEIGHT IN KG,Style,Bend Diameter
0,8 mm,1135 mm,1483.00 cm³,1752.0,1644.0,29503 mm,26,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,11.656372,Stirrup / Tie,64 mm
1,8 mm,1135 mm,456.31 cm³,1752.0,1644.0,9078 mm,8,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,3.586576,Stirrup / Tie,64 mm
2,8 mm,1135 mm,798.54 cm³,1752.0,1644.0,15886 mm,14,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,6.276508,Stirrup / Tie,64 mm
3,8 mm,1135 mm,1483.00 cm³,1752.0,1644.0,29503 mm,26,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,11.656372,Stirrup / Tie,64 mm
4,8 mm,1135 mm,1597.08 cm³,1752.0,1644.0,31773 mm,28,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,12.553016,Stirrup / Tie,64 mm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6004,25 mm,6000 mm,70684.65 cm³,205.0,205.0,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,175 mm
6005,25 mm,8000 mm,94252.82 cm³,204.0,204.0,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,175 mm
6006,25 mm,6000 mm,70684.65 cm³,205.0,205.0,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,175 mm
6007,25 mm,8000 mm,94252.82 cm³,204.0,204.0,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,175 mm
6008,25 mm,6000 mm,70684.65 cm³,205.0,205.0,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,175 mm

In [17]:
df['Workset'].unique()

array(['STR-Air Cooled Plant', 'STR-OUTER STRUCTURES'], dtype=object)

<span style="font-size:2em; color:orange;"><b>Exploratory Data Analysis</b></span>


### CHART 1: No. of steel bars for each diameter for whole project

In [18]:
df['Bar Diameter Num'] = df['Bar Diameter'].str.replace(' mm', '').astype(float)
df['Total Bar Length Num'] = df['Total Bar Length'].str.replace(' mm', '').astype(float)

In [19]:
# 1. Get the unique, sorted bar diameters from your dataset
unique_diameters = sorted(df['Bar Diameter Num'].dropna().unique())

fig_uni = px.histogram(
    df, 
    x='Bar Diameter Num', 
    title='Count of Rebar by Diameter',
    labels={'Bar Diameter Num': 'Bar Diameter (mm)'},
    text_auto=True,          
    width=1000, height=600    
)

fig_uni.update_layout(bargap=0.2)

# 2. Force the X-axis to ONLY show these exact unique values
fig_uni.update_xaxes(tickvals=unique_diameters)

fig_uni.show()

### CHART 2: Bar count for building and outer area surrounding structures

In [20]:
fig_workset = px.histogram(
    df, 
    x='Workset', 
    title='Rebars Count by Structure Area',
    labels={'Workset': 'Project Workset'},
    text_auto=True,
    width=1000, height=600  
)

fig_workset.show()

### CHART 3: Bar count by diameter for building and outer area surrounding structures

In [21]:
# A grouped histogram showing the breakdown of Bar Diameters for Building and Outer Structures
fig_workset_dia = px.histogram(
    df, 
    x='Workset', 
    color='Bar Diameter',      # This splits the bars by diameter
    barmode='group',           # Places the split bars side-by-side instead of stacking them
    title='Bar Diameter Count for Each Structure Area',
    text_auto=True,
    width=1000, height=600  
)

fig_workset_dia.update_layout(bargap=0.2)
fig_workset_dia.show()

### CHART 4: Bar count by host category for building and outer area surrounding structures

In [22]:
# Create a grouped histogram to compare Worksets across different Host Categories
fig_host_workset = px.histogram(
    df, 
    x='Host Category', 
    color='Workset', 
    barmode='group',           # Displays the bars side-by-side instead of stacked
    title='Rebar Count for Each Structural Element Type and Structure Area',
    text_auto=True,            # Shows the exact count on top of the bars
    width=1000, height=600                
)

# Add some gap between the bars for better readability
fig_host_workset.update_layout(bargap=0.2)

# Display the chart
fig_host_workset.show()

### CHART 5: Bar Lengths by host category

In [23]:
# 1. Clean the target column to numeric (just in case it hasn't been done yet)
df['Maximum bar length Num'] = df['Maximum bar length'].astype(str).str.replace(' mm', '').astype(float)
df

,Bar Diameter,Maximum bar length,Reinforcement Volume,Rebar Number,Mark,Total Bar Length,Quantity,Workset,Host Category,Host Mark,REBAR-PARTITION,WEIGHT IN KG,Style,Bend Diameter,Bar Diameter Num,Total Bar Length Num,Maximum bar length Num
0,8 mm,1135 mm,1483.00 cm³,1752.0,1644.0,29503 mm,26,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,11.656372,Stirrup / Tie,64 mm,8.0,29503.0,1135.0
1,8 mm,1135 mm,456.31 cm³,1752.0,1644.0,9078 mm,8,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,3.586576,Stirrup / Tie,64 mm,8.0,9078.0,1135.0
2,8 mm,1135 mm,798.54 cm³,1752.0,1644.0,15886 mm,14,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,6.276508,Stirrup / Tie,64 mm,8.0,15886.0,1135.0
3,8 mm,1135 mm,1483.00 cm³,1752.0,1644.0,29503 mm,26,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,11.656372,Stirrup / Tie,64 mm,8.0,29503.0,1135.0
4,8 mm,1135 mm,1597.08 cm³,1752.0,1644.0,31773 mm,28,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,12.553016,Stirrup / Tie,64 mm,8.0,31773.0,1135.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6004,25 mm,6000 mm,70684.65 cm³,205.0,205.0,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,175 mm,25.0,143998.0,6000.0
6005,25 mm,8000 mm,94252.82 cm³,204.0,204.0,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,175 mm,25.0,192010.0,8000.0
6006,25 mm,6000 mm,70684.65 cm³,205.0,205.0,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,175 mm,25.0,143998.0,6000.0
6007,25 mm,8000 mm,94252.82 cm³,204.0,204.0,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,175 mm,25.0,192010.0,8000.0
6008,25 mm,6000 mm,70684.65 cm³,205.0,205.0,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,175 mm,25.0,143998.0,6000.0

In [24]:
# 2. Group the data so we get one clean point per Bar Diameter
df_grouped = df.groupby('Bar Diameter Num', as_index=False)['Maximum bar length Num'].max()
df_grouped

   Bar Diameter Num  Maximum bar length Num
0               8.0                  2655.0
1              10.0                 12000.0
2              12.0                 12002.0
3              14.0                  1484.0
4              16.0                 12058.0
5              20.0                 12001.0
6              25.0                 12000.0

In [25]:
# Get the exact unique diameters used in your project (e.g., 8, 10, 12, 16, 25)
unique_diameters = sorted(df['Bar Diameter Num'].dropna().unique())

# 3. Create the scatter plot
fig_scatter = px.scatter(
    df,
    x='Bar Diameter Num',
    y='Maximum bar length Num',
    color='Host Category',       # Colors the dots based on Beam, Column, Wall, etc.
    title='Bar Lengths for Each Bar Diameter by Structural Element Type',
    labels={
        'Bar Diameter Num': 'Bar Diameter (mm)',
        'Maximum bar length Num': 'Maximum Length (mm)'
    },
    opacity=0.7,                 # Makes dots slightly transparent to see overlaps
    width=1000,                   
    height=600                   
)

# 4. Force the X-axis to ONLY show the actual used diameters (no multiples of 5)
fig_scatter.update_xaxes(tickvals=unique_diameters)

# Display the chart
fig_scatter.show()

### CHART 6: Steel Bar style quantity

In [26]:
# Create a chart summing up the total Quantity for each Style
fig_style_qty = px.histogram(
    df,
    x='Style',
    y='Quantity',
    histfunc='sum',            # Adds up the 'Quantity' column instead of just counting rows
    title='Rebar Style',
    labels={'Quantity': 'Total Quantity'},
    text_auto=True,            # Displays the total sum on top of each bar
    width=1000,                 
    height=600                 
)

# Add a gap between the bars for a cleaner look
fig_style_qty.update_layout(bargap=0.2)

# Display the chart
fig_style_qty.show()

### CHART 7: Each Bar Diameter Total Weight Per Structure Type

In [27]:
fig_weight = px.histogram(
    df,
    x='Bar Diameter Num',
    y='WEIGHT IN KG',
    color='Workset',
    histfunc='sum',            # Adds up the weights instead of counting rows
    barmode='group',           # Places the Workset bars side-by-side
    title='Total Weight (kg) For Each Bar Diameter and Structure type',
    labels={
        'Bar Diameter Num': 'Bar Diameter (mm)',
        'WEIGHT IN KG': 'Total Weight (kg)'
    },
    text_auto='.0f',           # Displays the sum rounded to 0 decimal places for clean reading
    width=1000,                 
    height=600                 
)

# 3. Clean up the layout and force exact X-axis ticks
fig_weight.update_layout(bargap=0.1)
fig_weight.update_xaxes(tickvals=unique_diameters)

# Display the chart
fig_weight.show()


<span style="font-size:2em; color:orange;"><b>Machine Learning Phase</b></span>

### Data Cleaning

In [28]:
# Drop the unnecessary columns
df = df.drop(columns=['Rebar Number', 'Mark', 'Bend Diameter'])

print(df.columns)

Index(['Bar Diameter', 'Maximum bar length', 'Reinforcement Volume',
       'Total Bar Length', 'Quantity', 'Workset', 'Host Category', 'Host Mark',
       'REBAR-PARTITION', 'WEIGHT IN KG', 'Style', 'Bar Diameter Num',
       'Total Bar Length Num', 'Maximum bar length Num'],
      dtype='object')

In [29]:
df

,Bar Diameter,Maximum bar length,Reinforcement Volume,Total Bar Length,Quantity,Workset,Host Category,Host Mark,REBAR-PARTITION,WEIGHT IN KG,Style,Bar Diameter Num,Total Bar Length Num,Maximum bar length Num
0,8 mm,1135 mm,1483.00 cm³,29503 mm,26,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,11.656372,Stirrup / Tie,8.0,29503.0,1135.0
1,8 mm,1135 mm,456.31 cm³,9078 mm,8,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,3.586576,Stirrup / Tie,8.0,9078.0,1135.0
2,8 mm,1135 mm,798.54 cm³,15886 mm,14,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,6.276508,Stirrup / Tie,8.0,15886.0,1135.0
3,8 mm,1135 mm,1483.00 cm³,29503 mm,26,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,11.656372,Stirrup / Tie,8.0,29503.0,1135.0
4,8 mm,1135 mm,1597.08 cm³,31773 mm,28,STR-Air Cooled Plant,Structural Framing,B 250X400,Beam,12.553016,Stirrup / Tie,8.0,31773.0,1135.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6004,25 mm,6000 mm,70684.65 cm³,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,25.0,143998.0,6000.0
6005,25 mm,8000 mm,94252.82 cm³,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,25.0,192010.0,8000.0
6006,25 mm,6000 mm,70684.65 cm³,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,25.0,143998.0,6000.0
6007,25 mm,8000 mm,94252.82 cm³,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,25.0,192010.0,8000.0
6008,25 mm,6000 mm,70684.65 cm³,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,25.0,143998.0,6000.0

## Focus on "Structural Columns" for ML Model

### 1. Filtration

In [30]:
# 1. Create a new dataframe that ONLY contains Structural Columns
df_columns = df[df['Host Category'] == 'Structural Column'].copy()

# Print the shape to see how many rows we have left
print(f"Number of Structural Column rows: {len(df_columns)}")

# Show a few unique Host Marks to confirm what the text looks like
print("Sample Host Marks:")
print(df_columns['Host Mark'].unique()[:5])

Number of Structural Column rows: 972
Sample Host Marks:
['ST-C1 250x400x8275' nan 'OS MEP SUPPORT' 'C3 400x400x7500'
 'PD1 300x300x2000']

In [31]:
df_columns

,Bar Diameter,Maximum bar length,Reinforcement Volume,Total Bar Length,Quantity,Workset,Host Category,Host Mark,REBAR-PARTITION,WEIGHT IN KG,Style,Bar Diameter Num,Total Bar Length Num,Maximum bar length Num
15,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0
16,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0
17,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0
18,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0
19,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6004,25 mm,6000 mm,70684.65 cm³,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,25.0,143998.0,6000.0
6005,25 mm,8000 mm,94252.82 cm³,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,25.0,192010.0,8000.0
6006,25 mm,6000 mm,70684.65 cm³,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,25.0,143998.0,6000.0
6007,25 mm,8000 mm,94252.82 cm³,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,25.0,192010.0,8000.0
6008,25 mm,6000 mm,70684.65 cm³,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,25.0,143998.0,6000.0

In [32]:
df_columns['Host Mark'].unique()

array(['ST-C1 250x400x8275', nan, 'OS MEP SUPPORT', 'C3 400x400x7500',
       'PD1 300x300x2000', 'C1 900x900x10500', 'C2 700x700x10500',
       'C4 500x500x10500', 'ST-C2 300x700x2000', 'ST-C2 250x700x8900',
       'ST-C3 250x900x8865', 'ST-C3 300x900x2000', 'PD2 400x550x2900',
       'PD2 400x550x4400', 'PD3 800x900x2900', 'PD4 400x900x2900',
       'PD4 400x900x4400', 'PD5 550x800x2900', 'PD0 300x300x1070',
       'P2 650X400X1250', 'P1 400X400X1250', 'AHU SHADE',
       'PC2 550X1300X1050', 'PC1 550X550'], dtype=object)

In [ ]:
# Replace "AHU SHADE" with the new dimensional label
df_columns['Host Mark'] = df_columns['Host Mark'].replace('AHU SHADE', 'P5 400x450x1400')
print(df_columns['Host Mark'].unique())

['ST-C1 250x400x8275' nan 'OS MEP SUPPORT' 'C3 400x400x7500'
 'PD1 300x300x2000' 'C1 900x900x10500' 'C2 700x700x10500'
 'C4 500x500x10500' 'ST-C2 300x700x2000' 'ST-C2 250x700x8900'
 'ST-C3 250x900x8865' 'ST-C3 300x900x2000' 'PD2 400x550x2900'
 'PD2 400x550x4400' 'PD3 800x900x2900' 'PD4 400x900x2900'
 'PD4 400x900x4400' 'PD5 550x800x2900' 'PD0 300x300x1070'
 'P2 650X400X1250' 'P1 400X400X1250' 'P5 400x450x1400' 'PC2 550X1300X1050'
 'PC1 550X550']

### 2. Extract Dimensions

In [35]:
# 2. Extract Length, Width, and Height using string extraction
extracted_dims = df_columns['Host Mark'].str.extract(r'(\d+)x(\d+)x(\d+)')

# Assign the extracted columns to our dataframe and convert them to decimals (float)
df_columns['Column_Length'] = extracted_dims[0].astype(float)
df_columns['Column_Width'] = extracted_dims[1].astype(float)
df_columns['Column_Height'] = extracted_dims[2].astype(float)

# Drop any rows where it failed to find the "L x W x H" pattern 
# (e.g., if there was a column just named "C1" with no numbers)
df_columns = df_columns.dropna(subset=['Column_Length', 'Column_Width', 'Column_Height'])

# Print to verify the extraction worked perfectly
print(df_columns[['Host Mark', 'Column_Length', 'Column_Width', 'Column_Height']])

               Host Mark  Column_Length  Column_Width  Column_Height
15    ST-C1 250x400x8275          250.0         400.0         8275.0
16    ST-C1 250x400x8275          250.0         400.0         8275.0
17    ST-C1 250x400x8275          250.0         400.0         8275.0
18    ST-C1 250x400x8275          250.0         400.0         8275.0
19    ST-C1 250x400x8275          250.0         400.0         8275.0
...                  ...            ...           ...            ...
6004    C1 900x900x10500          900.0         900.0        10500.0
6005    C1 900x900x10500          900.0         900.0        10500.0
6006    C1 900x900x10500          900.0         900.0        10500.0
6007    C1 900x900x10500          900.0         900.0        10500.0
6008    C1 900x900x10500          900.0         900.0        10500.0

[473 rows x 4 columns]

C:\Users\pc\AppData\Local\Temp\ipykernel_23188\1416897183.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\pc\AppData\Local\Temp\ipykernel_23188\1416897183.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\pc\AppData\Local\Temp\ipykernel_23188\1416897183.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [36]:
df_columns

,Bar Diameter,Maximum bar length,Reinforcement Volume,Total Bar Length,Quantity,Workset,Host Category,Host Mark,REBAR-PARTITION,WEIGHT IN KG,Style,Bar Diameter Num,Total Bar Length Num,Maximum bar length Num,Column_Length,Column_Width,Column_Height
15,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0,250.0,400.0,8275.0
16,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0,250.0,400.0,8275.0
17,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0,250.0,400.0,8275.0
18,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0,250.0,400.0,8275.0
19,8 mm,1135 mm,3422.31 cm³,68085 mm,60,STR-Air Cooled Plant,Structural Column,ST-C1 250x400x8275,Column,26.899320,Stirrup / Tie,8.0,68085.0,1135.0,250.0,400.0,8275.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6004,25 mm,6000 mm,70684.65 cm³,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,25.0,143998.0,6000.0,900.0,900.0,10500.0
6005,25 mm,8000 mm,94252.82 cm³,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,25.0,192010.0,8000.0,900.0,900.0,10500.0
6006,25 mm,6000 mm,70684.65 cm³,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,25.0,143998.0,6000.0,900.0,900.0,10500.0
6007,25 mm,8000 mm,94252.82 cm³,192010 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,740.827164,Standard,25.0,192010.0,8000.0,900.0,900.0,10500.0
6008,25 mm,6000 mm,70684.65 cm³,143998 mm,24,STR-Air Cooled Plant,Structural Column,C1 900x900x10500,Column,555.581327,Standard,25.0,143998.0,6000.0,900.0,900.0,10500.0

### 3. Grouping Data

In [37]:
# 3. Group the data by the column dimensions and the bar diameter
df_ml_ready = df_columns.groupby(
    ['Column_Length', 'Column_Width', 'Column_Height', 'Bar Diameter Num'], 
    as_index=False
)['WEIGHT IN KG'].sum()

# Rename the weight column to be clearer for our ML model
df_ml_ready = df_ml_ready.rename(columns={'WEIGHT IN KG': 'Total_Weight_KG'})

# Display the final, Machine Learning-ready dataset!
print("Final ML Ready Dataset:")
print(df_ml_ready.head(10))

Final ML Ready Dataset:
   Column_Length  Column_Width  Column_Height  Bar Diameter Num  \
0          250.0         400.0         8275.0               8.0
1          250.0         400.0         8275.0              10.0
2          250.0         400.0         8275.0              16.0
3          250.0         700.0         8900.0              10.0
4          250.0         700.0         8900.0              16.0
5          250.0         900.0         8865.0              10.0
6          250.0         900.0         8865.0              16.0
7          300.0         300.0         1070.0              10.0
8          300.0         300.0         1070.0              20.0
9          300.0         300.0         2000.0              10.0

   Total_Weight_KG
0       288.719368
1        44.194163
2      1164.568680
3       102.321429
4       102.733312
5       145.739680
6       227.623427
7        51.665832
8       202.277124
9         4.723012

## We will use 3 types of algorithms (Linear Regression, Random Forest Regressor, K-Nearest Neighbors (KNN))

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, r2_score

### Define Features and Split the Data

In [39]:
# 1. Define inputs (X) and what we want to predict (y)
X = df_ml_ready[['Column_Length', 'Column_Width', 'Column_Height', 'Bar Diameter Num']]
y = df_ml_ready['Total_Weight_KG']

# 2. Split into Training (80%) and Testing (20%) sets
# random_state=42 ensures we get the exact same random split every time we run this cell
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training Data: {X_train.shape[0]} rows")
print(f"Testing Data: {X_test.shape[0]} rows")

Training Data: 30 rows
Testing Data: 8 rows

### Build the 3 Pipelines

In [40]:
# Pipeline 1: Linear Regression
pipeline_lr = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

# Pipeline 2: Random Forest Regressor
pipeline_rf = Pipeline([
    ('scaler', StandardScaler()), 
    ('model', RandomForestRegressor(n_estimators=100, random_state=42))
])

# Pipeline 3: K-Nearest Neighbors (KNN)
pipeline_knn = Pipeline([
    ('scaler', StandardScaler()), 
    ('model', KNeighborsRegressor(n_neighbors=5))
])

# Store them in a dictionary for easy looping in the next step
pipelines = {
    'Linear Regression': pipeline_lr,
    'Random Forest': pipeline_rf,
    'K-Nearest Neighbors': pipeline_knn
}

print("Pipelines successfully created!")

Pipelines successfully created!

In [45]:
from sklearn import set_config

# 1. Turn on the visual diagram display feature
set_config(display='diagram')

In [ ]:
pipeline_lr

Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])

In [46]:
pipeline_rf

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', RandomForestRegressor(random_state=42))])

In [47]:
pipeline_knn

Pipeline(steps=[('scaler', StandardScaler()), ('model', KNeighborsRegressor())])

### Train and Evaluate the Models

In [48]:
results = []

# Loop through our dictionary of pipelines
for name, pipeline in pipelines.items():
    
    # 1. TRAIN: The pipeline scales X_train and fits the model to y_train
    pipeline.fit(X_train, y_train)
    
    # 2. PREDICT: The pipeline automatically scales X_test and makes predictions
    y_pred = pipeline.predict(X_test)
    
    # 3. EVALUATE: Compare predictions (y_pred) to the actual hidden answers (y_test)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    # Save the results
    results.append({
        'Model Name': name, 
        'R-Squared Score': round(r2, 4),
        'Mean Absolute Error (KG)': round(mae, 2)
    })

# Convert results to a dataframe and sort by best R-Squared score
results_df = pd.DataFrame(results).sort_values(by='R-Squared Score', ascending=False)

print("🏆 Final Model Evaluation 🏆")
display(results_df)

🏆 Final Model Evaluation 🏆

            Model Name  R-Squared Score  Mean Absolute Error (KG)
2  K-Nearest Neighbors           0.7356                    522.34
1        Random Forest           0.2809                    600.64
0    Linear Regression          -0.2368                   1415.34